### PR TITLE
dan-bock added more info about st paul

### PR DESCRIPTION
**Pull request by dan-bock**
Adding more info about st paul

### CODE REVIEW

**Comment by dan-bock** [comment]
@kevin-charpentier care to review this for me!??!

**Comment by dan-bock** [comment]
@kevin-charpentier any day now, thanks sir!

**Review by kevin-charpentier — APPROVED** [review]
looks good

**Comment by kevin-charpentier** [comment]
@dan-bock thanks for the million e-mails

**Comment by dan-bock** [comment]
@kevin-charpentier anytime

**Comment by dan-bock** [comment]
@kevin-charpentier you could mute this puppy if you want

**Pull request merged**
